######################################################################
# Automatically generated by qmake (2.01a) Mon Aug 24 10:25:39 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MainWindow.h FieldView.h
SOURCES += MainWindow.cc FieldView.cc main.cc
