######################################################################
# Automatically generated by qmake (2.01a) Mon Aug 24 10:25:39 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += src
INCLUDEPATH += src
OBJECTS_DIR = build
MOC_DIR = build
RCC_DIR = build
RESOURCES = gfx/gfx.qrc
ICON = gfx/icon1.icns

# Input
HEADERS += GameView.h MainWindow.h FieldView.h
SOURCES += GameView.cc MainWindow.cc FieldView.cc main.cc
