######################################################################
# Automatically generated by qmake (2.01a) Mon Aug 24 10:25:39 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
RESOURCES = gfx/gfx.qrc

# Input
HEADERS += GameView.h MainWindow.h FieldView.h
SOURCES += GameView.cc MainWindow.cc FieldView.cc main.cc
